### ISSUE TITLE
Error Export file

### ISSUE THREAD

**Issue by ondrejkoberec** [alphazolam/fmt_RE_MESH-Noesis-Plugin#22]
hello I have an issue if i want to export mesh this happend what did I do wrong I am stupid. Can you help me??
![image](https://github.com/alphazolam/fmt_RE_MESH-Noesis-Plugin/assets/164906056/5d94f450-899d-4dd8-90aa-d303aca09c04)

**Comment by Snailtron** [comment]
I'm having this same issue exporting.

**Comment by davarman30** [comment]
A solution for this?
I'm having this same issue

**Comment by alphazolam** [comment]
That was my mistake, sorry. Its fixed now
