### ISSUE TITLE
fmt_RE_MESH-Noesis-Plugin rename object and bug mesh

### ISSUE THREAD

**Issue by Devastator455** [alphazolam/fmt_RE_MESH-Noesis-Plugin#3]
Hello
When import or export, the plugin rename for example 
LODGroup_1_Group_0_SubMesh_1__collarfur_alp2  rename to 
LOD_1_Group_0_Sub_1__collarfur_alp2 causing error for mesh in the game (MHR).
My last plugin do not rename i tried

Sorry for my language him french and my english it's medium.

**Comment by alphazolam** [comment]
You can change the option "bShorterNames" to False at the top of the fmt_RE_MESH.py file to use the longer old names
