### ISSUE TITLE
Missing list code for RE:Verse

### ISSUE THREAD

**Issue by boutoron2685** [alphazolam/fmt_RE_MESH-Noesis-Plugin#5]
![스크린샷 2023-03-12 191131](https://user-images.githubusercontent.com/16276011/224538389-cc3005a0-c8ba-42c8-9f03-286767d243a8.png)
![스크린샷 2023-03-12 192325](https://user-images.githubusercontent.com/16276011/224538568-87397f23-e2b7-4930-a19f-2bf361127d5f.png)

![스크린샷 2023-03-12 191739](https://user-images.githubusercontent.com/16276011/224538520-21777b23-dd45-4c4a-aef2-97593f5da498.png)
![스크린샷 2023-03-12 191938](https://user-images.githubusercontent.com/16276011/224538526-87c6b5e3-eccf-4078-ba65-11bd7bf7a8fa.png)

The newly updated GUI plugin did not recognize "Re:Verse". I checked the file and found that the code to read the file exists, but the game list is missing, so the file cannot be loaded. I added "REVerse" myself and it worked fine.

**Comment by DaniGP17** [comment]
If it work you can make a pull request to this repository

**Comment by boutoron2685** [comment]
> Sorry, I wasn't familiar with GitHub's pull requests.
