### ISSUE TITLE
RE4 remake mesh appears to be the wrong number and i cant get the mesh to render in noesis

### ISSUE THREAD

**Issue by Batman645** [alphazolam/fmt_RE_MESH-Noesis-Plugin#7]
first time doing this so if i just missed a step feel free to let me know. Attempting to make a mod (first time so attempting a guide), I put the code in the python folder, extracted re4 demo pak with out a file list so going blind and i go to look at the re4r mesh divider and nothing appears, re4r textures appear so i know that code works, and when i check in the folder i extracted to i see meshes at a different file type and they wont render in noesis.

**Comment by alphazolam** [comment]
You need to use a file list. You can find one on Ekey's [REE.PAK.Tool](https://github.com/Ekey/REE.PAK.Tool/tree/main/Projects) page
