### ISSUE TITLE
Import LODs is non functional

### ISSUE THREAD

**Issue by Roachdaripper** [alphazolam/fmt_RE_MESH-Noesis-Plugin#9]
Self-explanatory title, when exporting a model via Noesis, the LOD tickbox does nothing, and it still only exports the highest LOD.

**Comment by alphazolam** [comment]
I removed the checkbox, it shouldn't have been visible. I might re add it at some point if I decide to implement it. For now you can export models from most games to MESH with LODs using the old 3dsmax "RE Engine MESH Tool" script
